language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - coverage run test_ABBA.py -v

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
