# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_Ckmeans')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_Ckmeans')
    _Ckmeans = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Ckmeans', [dirname(__file__)])
        except ImportError:
            import _Ckmeans
            return _Ckmeans
        try:
            _mod = imp.load_module('_Ckmeans', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _Ckmeans = swig_import_helper()
    del swig_import_helper
else:
    import _Ckmeans
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _Ckmeans.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self) -> "PyObject *":
        return _Ckmeans.SwigPyIterator_value(self)

    def incr(self, n: 'size_t'=1) -> "swig::SwigPyIterator *":
        return _Ckmeans.SwigPyIterator_incr(self, n)

    def decr(self, n: 'size_t'=1) -> "swig::SwigPyIterator *":
        return _Ckmeans.SwigPyIterator_decr(self, n)

    def distance(self, x: 'SwigPyIterator') -> "ptrdiff_t":
        return _Ckmeans.SwigPyIterator_distance(self, x)

    def equal(self, x: 'SwigPyIterator') -> "bool":
        return _Ckmeans.SwigPyIterator_equal(self, x)

    def copy(self) -> "swig::SwigPyIterator *":
        return _Ckmeans.SwigPyIterator_copy(self)

    def next(self) -> "PyObject *":
        return _Ckmeans.SwigPyIterator_next(self)

    def __next__(self) -> "PyObject *":
        return _Ckmeans.SwigPyIterator___next__(self)

    def previous(self) -> "PyObject *":
        return _Ckmeans.SwigPyIterator_previous(self)

    def advance(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator *":
        return _Ckmeans.SwigPyIterator_advance(self, n)

    def __eq__(self, x: 'SwigPyIterator') -> "bool":
        return _Ckmeans.SwigPyIterator___eq__(self, x)

    def __ne__(self, x: 'SwigPyIterator') -> "bool":
        return _Ckmeans.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator &":
        return _Ckmeans.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator &":
        return _Ckmeans.SwigPyIterator___isub__(self, n)

    def __add__(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator *":
        return _Ckmeans.SwigPyIterator___add__(self, n)

    def __sub__(self, *args) -> "ptrdiff_t":
        return _Ckmeans.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _Ckmeans.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class double_vector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, double_vector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, double_vector, name)
    __repr__ = _swig_repr

    def iterator(self) -> "swig::SwigPyIterator *":
        return _Ckmeans.double_vector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self) -> "bool":
        return _Ckmeans.double_vector___nonzero__(self)

    def __bool__(self) -> "bool":
        return _Ckmeans.double_vector___bool__(self)

    def __len__(self) -> "std::vector< double >::size_type":
        return _Ckmeans.double_vector___len__(self)

    def __getslice__(self, i: 'std::vector< double >::difference_type', j: 'std::vector< double >::difference_type') -> "std::vector< double,std::allocator< double > > *":
        return _Ckmeans.double_vector___getslice__(self, i, j)

    def __setslice__(self, *args) -> "void":
        return _Ckmeans.double_vector___setslice__(self, *args)

    def __delslice__(self, i: 'std::vector< double >::difference_type', j: 'std::vector< double >::difference_type') -> "void":
        return _Ckmeans.double_vector___delslice__(self, i, j)

    def __delitem__(self, *args) -> "void":
        return _Ckmeans.double_vector___delitem__(self, *args)

    def __getitem__(self, *args) -> "std::vector< double >::value_type const &":
        return _Ckmeans.double_vector___getitem__(self, *args)

    def __setitem__(self, *args) -> "void":
        return _Ckmeans.double_vector___setitem__(self, *args)

    def pop(self) -> "std::vector< double >::value_type":
        return _Ckmeans.double_vector_pop(self)

    def append(self, x: 'std::vector< double >::value_type const &') -> "void":
        return _Ckmeans.double_vector_append(self, x)

    def empty(self) -> "bool":
        return _Ckmeans.double_vector_empty(self)

    def size(self) -> "std::vector< double >::size_type":
        return _Ckmeans.double_vector_size(self)

    def swap(self, v: 'double_vector') -> "void":
        return _Ckmeans.double_vector_swap(self, v)

    def begin(self) -> "std::vector< double >::iterator":
        return _Ckmeans.double_vector_begin(self)

    def end(self) -> "std::vector< double >::iterator":
        return _Ckmeans.double_vector_end(self)

    def rbegin(self) -> "std::vector< double >::reverse_iterator":
        return _Ckmeans.double_vector_rbegin(self)

    def rend(self) -> "std::vector< double >::reverse_iterator":
        return _Ckmeans.double_vector_rend(self)

    def clear(self) -> "void":
        return _Ckmeans.double_vector_clear(self)

    def get_allocator(self) -> "std::vector< double >::allocator_type":
        return _Ckmeans.double_vector_get_allocator(self)

    def pop_back(self) -> "void":
        return _Ckmeans.double_vector_pop_back(self)

    def erase(self, *args) -> "std::vector< double >::iterator":
        return _Ckmeans.double_vector_erase(self, *args)

    def __init__(self, *args):
        this = _Ckmeans.new_double_vector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x: 'std::vector< double >::value_type const &') -> "void":
        return _Ckmeans.double_vector_push_back(self, x)

    def front(self) -> "std::vector< double >::value_type const &":
        return _Ckmeans.double_vector_front(self)

    def back(self) -> "std::vector< double >::value_type const &":
        return _Ckmeans.double_vector_back(self)

    def assign(self, n: 'std::vector< double >::size_type', x: 'std::vector< double >::value_type const &') -> "void":
        return _Ckmeans.double_vector_assign(self, n, x)

    def resize(self, *args) -> "void":
        return _Ckmeans.double_vector_resize(self, *args)

    def insert(self, *args) -> "void":
        return _Ckmeans.double_vector_insert(self, *args)

    def reserve(self, n: 'std::vector< double >::size_type') -> "void":
        return _Ckmeans.double_vector_reserve(self, n)

    def capacity(self) -> "std::vector< double >::size_type":
        return _Ckmeans.double_vector_capacity(self)
    __swig_destroy__ = _Ckmeans.delete_double_vector
    __del__ = lambda self: None
double_vector_swigregister = _Ckmeans.double_vector_swigregister
double_vector_swigregister(double_vector)

class int_vector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, int_vector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, int_vector, name)
    __repr__ = _swig_repr

    def iterator(self) -> "swig::SwigPyIterator *":
        return _Ckmeans.int_vector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self) -> "bool":
        return _Ckmeans.int_vector___nonzero__(self)

    def __bool__(self) -> "bool":
        return _Ckmeans.int_vector___bool__(self)

    def __len__(self) -> "std::vector< int >::size_type":
        return _Ckmeans.int_vector___len__(self)

    def __getslice__(self, i: 'std::vector< int >::difference_type', j: 'std::vector< int >::difference_type') -> "std::vector< int,std::allocator< int > > *":
        return _Ckmeans.int_vector___getslice__(self, i, j)

    def __setslice__(self, *args) -> "void":
        return _Ckmeans.int_vector___setslice__(self, *args)

    def __delslice__(self, i: 'std::vector< int >::difference_type', j: 'std::vector< int >::difference_type') -> "void":
        return _Ckmeans.int_vector___delslice__(self, i, j)

    def __delitem__(self, *args) -> "void":
        return _Ckmeans.int_vector___delitem__(self, *args)

    def __getitem__(self, *args) -> "std::vector< int >::value_type const &":
        return _Ckmeans.int_vector___getitem__(self, *args)

    def __setitem__(self, *args) -> "void":
        return _Ckmeans.int_vector___setitem__(self, *args)

    def pop(self) -> "std::vector< int >::value_type":
        return _Ckmeans.int_vector_pop(self)

    def append(self, x: 'std::vector< int >::value_type const &') -> "void":
        return _Ckmeans.int_vector_append(self, x)

    def empty(self) -> "bool":
        return _Ckmeans.int_vector_empty(self)

    def size(self) -> "std::vector< int >::size_type":
        return _Ckmeans.int_vector_size(self)

    def swap(self, v: 'int_vector') -> "void":
        return _Ckmeans.int_vector_swap(self, v)

    def begin(self) -> "std::vector< int >::iterator":
        return _Ckmeans.int_vector_begin(self)

    def end(self) -> "std::vector< int >::iterator":
        return _Ckmeans.int_vector_end(self)

    def rbegin(self) -> "std::vector< int >::reverse_iterator":
        return _Ckmeans.int_vector_rbegin(self)

    def rend(self) -> "std::vector< int >::reverse_iterator":
        return _Ckmeans.int_vector_rend(self)

    def clear(self) -> "void":
        return _Ckmeans.int_vector_clear(self)

    def get_allocator(self) -> "std::vector< int >::allocator_type":
        return _Ckmeans.int_vector_get_allocator(self)

    def pop_back(self) -> "void":
        return _Ckmeans.int_vector_pop_back(self)

    def erase(self, *args) -> "std::vector< int >::iterator":
        return _Ckmeans.int_vector_erase(self, *args)

    def __init__(self, *args):
        this = _Ckmeans.new_int_vector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x: 'std::vector< int >::value_type const &') -> "void":
        return _Ckmeans.int_vector_push_back(self, x)

    def front(self) -> "std::vector< int >::value_type const &":
        return _Ckmeans.int_vector_front(self)

    def back(self) -> "std::vector< int >::value_type const &":
        return _Ckmeans.int_vector_back(self)

    def assign(self, n: 'std::vector< int >::size_type', x: 'std::vector< int >::value_type const &') -> "void":
        return _Ckmeans.int_vector_assign(self, n, x)

    def resize(self, *args) -> "void":
        return _Ckmeans.int_vector_resize(self, *args)

    def insert(self, *args) -> "void":
        return _Ckmeans.int_vector_insert(self, *args)

    def reserve(self, n: 'std::vector< int >::size_type') -> "void":
        return _Ckmeans.int_vector_reserve(self, n)

    def capacity(self) -> "std::vector< int >::size_type":
        return _Ckmeans.int_vector_capacity(self)
    __swig_destroy__ = _Ckmeans.delete_int_vector
    __del__ = lambda self: None
int_vector_swigregister = _Ckmeans.int_vector_swigregister
int_vector_swigregister(int_vector)

class Output(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Output, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Output, name)
    __repr__ = _swig_repr
    __swig_setmethods__["cluster"] = _Ckmeans.Output_cluster_set
    __swig_getmethods__["cluster"] = _Ckmeans.Output_cluster_get
    if _newclass:
        cluster = _swig_property(_Ckmeans.Output_cluster_get, _Ckmeans.Output_cluster_set)
    __swig_setmethods__["centres"] = _Ckmeans.Output_centres_set
    __swig_getmethods__["centres"] = _Ckmeans.Output_centres_get
    if _newclass:
        centres = _swig_property(_Ckmeans.Output_centres_get, _Ckmeans.Output_centres_set)
    __swig_setmethods__["withinss"] = _Ckmeans.Output_withinss_set
    __swig_getmethods__["withinss"] = _Ckmeans.Output_withinss_get
    if _newclass:
        withinss = _swig_property(_Ckmeans.Output_withinss_get, _Ckmeans.Output_withinss_set)
    __swig_setmethods__["size"] = _Ckmeans.Output_size_set
    __swig_getmethods__["size"] = _Ckmeans.Output_size_get
    if _newclass:
        size = _swig_property(_Ckmeans.Output_size_get, _Ckmeans.Output_size_set)
    __swig_setmethods__["BIC"] = _Ckmeans.Output_BIC_set
    __swig_getmethods__["BIC"] = _Ckmeans.Output_BIC_get
    if _newclass:
        BIC = _swig_property(_Ckmeans.Output_BIC_get, _Ckmeans.Output_BIC_set)
    __swig_setmethods__["Kopt"] = _Ckmeans.Output_Kopt_set
    __swig_getmethods__["Kopt"] = _Ckmeans.Output_Kopt_get
    if _newclass:
        Kopt = _swig_property(_Ckmeans.Output_Kopt_get, _Ckmeans.Output_Kopt_set)

    def __init__(self, in_cluster: 'int_vector', in_centres: 'double_vector', in_withinss: 'double_vector', in_size: 'double_vector', in_BIC: 'double_vector', in_Kopt: 'size_t'):
        this = _Ckmeans.new_Output(in_cluster, in_centres, in_withinss, in_size, in_BIC, in_Kopt)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _Ckmeans.delete_Output
    __del__ = lambda self: None
Output_swigregister = _Ckmeans.Output_swigregister
Output_swigregister(Output)


def kmeans_1d_dp(x_v: 'double_vector', Kmin: 'size_t', Kmax: 'size_t', var: 'double', method: 'std::string const &') -> "Output":
    return _Ckmeans.kmeans_1d_dp(x_v, Kmin, Kmax, var, method)
kmeans_1d_dp = _Ckmeans.kmeans_1d_dp
# This file is compatible with both classic and new-style classes.


